#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Updating Blossom public URL"
max_upload_size_mb=$(( (max_upload_size + 1048575) / 1048576 ))
ynh_config_add --template="config.yml.j2" --destination="$install_dir/config.yml"
ynh_config_change_url_nginx
ynh_systemctl --service="$app" --action=restart
