#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Updating Blossom public URL"
max_upload_size="${max_upload_size:-2147483648}"
max_upload_size_mb=$(( (max_upload_size + 1048575) / 1048576 ))
ynh_config_change_url_nginx
ynh_systemctl --service="$app" --action=restart
