#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_app_config_apply() {
	ynh_systemctl --service="$app" --action=stop || true
	_ynh_app_config_apply
	max_upload_size="${max_upload_size:-2147483648}"
	max_upload_size="$(ynh_upload_size_to_bytes "$max_upload_size")"
	max_upload_size_mb=$(( (max_upload_size + 1048575) / 1048576 ))
	MAX_UPLOAD_SIZE_MB="$max_upload_size_mb"
	ynh_write_var_in_file --file="$install_dir/config.yml" --key="maxSize" --after="^upload:" --value="$max_upload_size"

	media_max_upload_size="${media_max_upload_size:-1073741824}"
	media_max_upload_size="$(ynh_upload_size_to_bytes "$media_max_upload_size")"
	ynh_write_var_in_file --file="$install_dir/config.yml" --key="maxSize" --after="^media:" --value="$media_max_upload_size"

	ynh_config_add_nginx
	ynh_systemctl --service="$app" --action=start --log_path=systemd --wait_until="Blossom Server listening"
}

ynh_app_config_run "$1"
