#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Removing Blossom Server"
ynh_systemd_action --service_name="$app" --action=stop || true
yunohost service remove "$app" || true
ynh_remove_systemd_config
ynh_remove_nginx_config
ynh_secure_remove --file="$install_dir"
ynh_secure_remove --file="$data_dir"
