#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Removing Blossom Server"
ynh_systemctl --service="$app" --action=stop || true
yunohost service remove "$app" || true
ynh_config_remove_systemd "$app"
ynh_config_remove_nginx
ynh_safe_rm "$install_dir"
ynh_safe_rm "$data_dir"
