#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_abort_if_errors
ynh_script_progression "Stopping Blossom Server"
ynh_systemd_action --service_name="$app" --action=stop || true

ynh_script_progression "Updating Blossom Server"
ynh_setup_source --source_id=main --dest_dir="$install_dir" --keep="config.yml,.deno-cache,data"
source_root="$(find "$install_dir" -mindepth 1 -maxdepth 1 -type d -name 'blossom-server-*' -print -quit)"
if [ -n "$source_root" ]; then
	shopt -s dotglob
	mv "$source_root"/* "$install_dir"/
	rmdir "$source_root"
	shopt -u dotglob
fi

export DENO_DIR="$install_dir/.deno-cache"
export PATH="$install_dir/.deno:$PATH"
pushd "$install_dir" >/dev/null
ynh_exec_and_print_stderr_only_if_error "$install_dir/.deno/deno task build"
popd >/dev/null

ynh_add_config --template="config.yml.j2" --destination="$install_dir/config.yml"
chown -R "$app:$app" "$install_dir" "$data_dir"
ynh_add_systemd_config --service="$app" --template="systemd.service"
ynh_add_nginx_config
ynh_systemd_action --service_name="$app" --action=start --log_path=systemd --line_match="Listening"
