#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_abort_if_errors
ynh_script_progression "Stopping Blossom Server"
ynh_systemctl --service="$app" --action=stop || true

ynh_script_progression "Updating Blossom Server"
ynh_setup_source --source_id=main --dest_dir="$install_dir" --keep="config.yml,.deno-cache,data"
ynh_setup_source --source_id=deno --dest_dir="$install_dir/.deno"
max_upload_size="${max_upload_size:-2147483648}"
max_upload_size_mb=$(( (max_upload_size + 1048575) / 1048576 ))
source_root="$(find "$install_dir" -mindepth 1 -maxdepth 1 -type d -name 'blossom-server-*' -print -quit)"
if [ -n "$source_root" ]; then
	shopt -s dotglob
	mv "$source_root"/* "$install_dir"/
	rmdir "$source_root"
	shopt -u dotglob
fi

export DENO_DIR="$install_dir/.deno-cache"
export PATH="$install_dir/.deno:$PATH"
pushd "$install_dir" >/dev/null
ynh_exec_and_print_stderr_only_if_error "$install_dir/.deno/deno" task build
popd >/dev/null

chown -R "$app:$app" "$install_dir" "$data_dir"
ynh_config_add_systemd --service="$app" --template="systemd.service"
ynh_config_add_nginx
ynh_systemctl --service="$app" --action=start --log_path=systemd --wait_until="Listening"
